[package]
name = "bdk-async-persist"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.0", features = ["postgres", "runtime-tokio-rustls"] }
thiserror = "1"
tokio = { version = "1.39.2", features = ["full"] }

[dependencies.bdk_wallet]
#path = "../bdk/crates/wallet"
git = "https://github.com/evanlinjin/bdk"
#branch = "simplify_wallet_persistence"
rev = "f434c93a788c6334319c40de7fe961113b9e415f"
